### ISSUE TITLE
工程编译少一个com.sunmi.printerhelper.R类

### ISSUE THREAD

**Issue by fc1986** [shangmisunmi/SunmiPrinterDemo#33]
我导入了这个工程，但编译的时候少了一个com.sunmi.printerhelper.R类，请问是少提交这个类吗，还是我哪里弄错了？麻烦尽快回复一下，在线等，急，谢谢！
![image](https://user-images.githubusercontent.com/61484209/75305066-fa33a180-587f-11ea-8908-180f65b468fe.png)

**Comment by git175010415** [comment]
这个资源类应该是编译后生成，你看下编译的情况

**Comment by fc1986** [comment]
![image](https://user-images.githubusercontent.com/61484209/75322049-071aba00-58ad-11ea-817c-7adeb65a6722.png)
![image](https://user-images.githubusercontent.com/61484209/75322062-0da93180-58ad-11ea-898b-c66a92e5646c.png)
![image](https://user-images.githubusercontent.com/61484209/75322067-11d54f00-58ad-11ea-9ae0-42bf4c39537a.png)
![image](https://user-images.githubusercontent.com/61484209/75322088-1994f380-58ad-11ea-8911-918d96e04410.png)
我的工程gradle编译是成功的

**Comment by git175010415** [comment]
检查下build或者rebuild后的情况，没有这个类一般是构建问题

**Comment by fc1986** [comment]
能麻烦把你的配置截图发出来吗？

**Comment by fc1986** [comment]
> 检查下build或者rebuild后的情况，没有这个类一般是构建问题

我换了一个版本的idea就可以了，还是谢谢你

**Comment by git175010415** [comment]
应该是新版本的Android Studio aapt会编译时自动生成了R类，已经转换为R.txt文件
