### ISSUE TITLE
SpiJni类 D2设备钱箱控制 没有执行权限

### ISSUE THREAD

**Issue by qinlang122** [shangmisunmi/SunmiPrinterDemo#34]
type=1400 audit(0.0:19490): avc: denied { write } for name="gpioctl" dev="sysfs" ino=18336 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_cashbox:s0 tclass=file permissive=0

**Comment by git175010415** [comment]
使用的是接口方式吗？如果是接口方式权限问题是由于系统版本的bug，最好升级下系统

**Comment by qinlang122** [comment]
不是的，由于你们提供的远程服务API，不支持打印机，所以没用那个方式，你们这个钱箱控制用的gpio，但是用你们写好的这个ApiJni类，执行方法的时候，报的没用权限执行gpio文件写入。

**Comment by git175010415** [comment]
最好不要这么用，我们为了适配不同钱箱，有一些逻辑控制，所以我们不支持直接用gpio控制，有权限控制
