### ISSUE TITLE
Not Able to Run SunmiPrinterService 

### ISSUE THREAD

**Issue by s9iper1** [shangmisunmi/SunmiPrinterDemo#52]
In your demo SunmiPrinterService is not running and on my own demo this service is not running, could you help me out here, thanks

**Comment by git175010415** [comment]
> In your demo SunmiPrinterService is not running and on my own demo this service is not running, could you help me out here, thanks

can you show me more details?

**Comment by NaderRaida** [comment]
Any update here?

**Comment by s9iper1** [comment]
This service only runs when you install and use your app on sunmi device.
