### ISSUE TITLE
 Barcode does not print '0' at the end

### ISSUE THREAD

**Issue by NidhinrajK** [shangmisunmi/SunmiPrinterDemo#81]
Barcode does not print '0' at the end

barcode data - "{C8904011507010"

Device Sunmi V2 Pro
SDK - "com.sunmi:printerlibrary:1.0.22"

![image](https://github.com/shangmisunmi/SunmiPrinterDemo/assets/139881688/757142ea-a410-4c6f-aa2d-66f0fc8ad493)

![WhatsApp Image 2024-02-23 at 17 54 53_af5d8f62](https://github.com/shangmisunmi/SunmiPrinterDemo/assets/139881688/44d6e897-92bd-40b5-b870-be3259861b00)

**Comment by git175010415** [comment]
Code 128C can only use even counts.
You can use {C890401150701{B0
